global:
  scrape_interval:     15s
  evaluation_interval: 15s
 
scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.95.40:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "192.168.95.10:9100"
          - "192.168.95.11:9100"
          - "192.168.95.12:9100"
          - "192.168.95.13:9100"
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: instance
        replacement: '${1}'

  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "192.168.95.10:8183"
          - "192.168.95.11:8183"
          - "192.168.95.12:8183"
          - "192.168.95.13:8183"
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: instance
        replacement: '${1}'
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: host
        replacement: '${1}'

  - job_name: "swarm-scheduler-exporter"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - "192.168.95.10:9323"
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):.*'
        target_label: instance
        replacement: '$1'
